### PR TITLE
Fix #47: Applying patch on Windows OS

### LINKED ISSUE #47: Patching is not working on Windows
I have updated to the latest version of the tool, and now I cannot use git istage. The tool is able to detect the changes, but I cannot stage any line or block, nor can I un-stage them.

istage-patch-error

Debugging the tool (using `git bisect` 😉), I found the issue started manifesting after PR #43.
One of the updates was [changing the way the patch file is created](https://github.com/terrajobst/git-istage/commit/f27cda35d1200c4ab9af6b41297dfc2afdbbc811#diff-1a617748b81e6fccd6757d7fe88df32102377686d1374c21ed8cf0a0887d0518L145-R145). It went from using `File.WriteAllText` to use `File.WriteAllLines`.

Then I compared the differences between these two methods (see image below), and I found that the latter introduces a `CRLF` instead of keeping the original `LF` character. So seems like in Windows OS, the method `File.WriteAllLines` will add that extra `CR` (`0x0D`) per line. This will result in a conflict when applying the patch. 

image

### PR DESCRIPTION
**Pull request by jmelosegui**

### CODE REVIEW

**Comment by terrajobst** [comment]
Ouch! Thanks for submitting this. Looks like #43 might have broken this. I recently noticed this too but didn’t investigate further. Looks like I need more test coverage for this because it differs greatly between Windows and Linux.

Right now I’m on a trip. I’ll investigate next week when I’m back.

**Review by terrajobst — APPROVED** [review]
Looks good but I want to add some test across operating systems to avoid future regressions. I won’t block the PR but I want to do some manual testing before merging (because that’s what I didn’t do last time 🥸)

**Comment by jmelosegui** [comment]
Thanks for your quick response.

> Ouch! Thanks for submitting this. Looks like #43 might have broken this. I recently noticed this too but didn’t investigate further. Looks like I need more test coverage for this because it differs greatly between Windows and Linux.

Yeah, I've described my findings in issue #47 

> I want to add some tests across operating systems to avoid future regressions.

I would like to contribute the test associated with my changes here.

This is what I have in mind:

- [ ] Mock the code running the `git apply` patch command.
This will allow to unit test the `ApplyPatch` method without executing the test against a real git repo.
It will require some sort of `IProcessRunner` and its implementation to abstract away the git command execution.
- [ ] Change the class `Patching` from static to an instance class.
 This allows the `Patching`  class to accept the `IProcessRunner` from the previous step as a constructor parameter.
- [ ] Read the temporary patch file created within the  `ApplyPatch` method and compare it against an expected result.
The code is using the `File` class to create the patch file and delete it before the `ApplyPatch` method returns. We can intercept the arguments passed to the  `IProcessRunner.Run` mocked method using [Moq Callbacks](https://github.com/Moq/moq4/wiki/Quickstart#callbacks) to read the generated temp file before it gets deleted.

If you think this is an appropriate approach, I can work on this and try to get it done before you are back.

Thoughts?

**Comment by yurikus** [comment]
Hi, any update on this? Would like this merged! Thanks!

**Comment by jmelosegui** [comment]
@yurikus, while I wait for @terrajobst to have some time to review this, I am using a nightly build version of the tool hosted on my own feed.

If you want to use it, run the following command on your computer.

```
dotnet tool update -g git-istage --version 0.3.59-g64a4c63489 --add-source https://f.feedz.io/jmelosegui/oss/nuget/index.json
```

Hope this helps.

**Comment by alirezanet** [comment]
Hi, Sorry if my PR broke something 😳, Today I updated my git-istage to the latest version suddenly it stopped working for me too! 
but I should note before that PR we had a lot of other problems with windows. #41. 

anyway, I really like this tool, Let me know if I can help to fix this problem.

**Comment by yurikus** [comment]
My workaround was to git config eol to auto, and renormalize everything. Having mixed eol settings in diffs is a problem. Hth. 

The tool is very useful, let's fix it together. 🙂

**Comment by alirezanet** [comment]
> My workaround was to git config eol to auto, and renormalize everything. Having mixed eol settings in diffs is a problem. Hth.
> 
> The tool is very useful, let's fix it together. 🙂

Yeah, I did the same thing.  I think it would be great if we add a CLI command to configure the repo automatically.

**Comment by yurikus** [comment]
Not always possible, some repos need to have eol=input.

**Comment by ubhaya** [comment]
hey complete the merge of this. istage it not working on windows without this

**Comment by DualBrain** [comment]
nudge.. nudge... nudgie... nudge-nudge-nudge. ;-) 

I saw this used in your videos and, until now, didn't have a great need to utilize it... but now I'm in a spot where this would be ultra-useful and, apparently since I'm on Windows... can't. :-(

**Comment by terrajobst** [comment]
Apologies: I just realized that I fixed the bug yesterday and forgot that there was a pending PR :-( I fixed it in 8c6bce5b576f297fd238e9685c26f2ba5592e758.

**Pull request closed without merging**
